# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa2cbbc6ddd1f0d85b34e46bb93f5ca971674e73a10b03c4246339453370d045a9c5e4f625561c462c03d3041062672ad08aa1d039138f409f698b6c2552fdab

test:
  secret_key_base: 3ca06cab17e833e96e8fffddbbd47aee9ae4c764f1442e4a26c8e13fd0c8e5e32c614ce83b873a365dacbd8bda785fd4a959cf818760a9711c648e81d1b07666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
